---
- hosts: masters
  name: install htpasswd users and set roles
  become: yes
  vars:
    admin_user: "admin"
    admin_pass: admin
    sys_admin_user: system
    username1: developer
    username2: developer2
    password: developer

  tasks:
    - debug: msg={{ admin_user }}
    - debug: msg={{ sys_admin_user }}
    - debug: msg={{ username1 }}
    - debug: msg={{ username2 }}

    - name: Install httpd-tools
      yum:
        name: httpd-tools
        state: present


    - name: Create admin user
      htpasswd:
        path: /etc/origin/master/htpasswd
        name: "{{ admin_user }}"
        password: "{{ admin_pass }}"

    - name: Create sys admin user
      htpasswd:
        path: /etc/origin/master/htpasswd
        name: "{{ sys_admin_user }}"
        password: "{{ admin_pass }}"

    - name: Create regular user
      htpasswd:
        path: /etc/origin/master/htpasswd
        name: "{{ username1 }}"
        password: "{{ password }}"

    - name: Create 2nd regular user
      htpasswd:
        path: /etc/origin/master/htpasswd
        name: "{{ username2 }}"
        password: "{{ password }}"

    - name: attach the cluster-admin role to admin via shell 
      shell: oc adm policy add-cluster-role-to-user cluster-admin {{ admin_user }} > ~/admin_role_result.txt
      ignore_errors: true
    - name: attach the cluster-admin role to system admin via shell 
      shell: oc adm policy add-cluster-role-to-user cluster-admin {{ sys_admin_user }} > ~/sys_admin_role_result.txt
      ignore_errors: true

    - name: echo output admin role results
      shell: cat ~/admin_role_result.txt
      register: admin_role_result

    - name: output admin role results
      debug: msg={{ admin_role_result.stdout }}

    - name: echo output sys admin role results
      shell: cat ~/sys_admin_role_result.txt
      register: sys_admin_role_result

    - name: output admin role results
      debug: msg={{ sys_admin_role_result.stdout }}

    - name: restart master
      service: 
        name: atomic-openshift-master-api
        state: restarted
