#to be run on storage node
apiVersion: v1
kind: PersistentVolume
labels:
  volume: createdpvs
metadata:
  name: volNNN
spec:
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteOnce     
    - ReadWriteMany
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/data/volNNN
